=== DalavanCloud/opac_schema/docs/v1/journal/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "/",
  "type": "object",
  "properties": {
    "copyrighter": {
      "id": "copyrighter",
      "type": "string"
    },
    "mission": {
      "id": "mission",
      "type": "array",
      "items": {
        "id": "2",
        "type": "object",
        "properties": {
          "description": {
            "id": "description",
            "type": "string"
          },
          "language": {
            "id": "language",
            "type": "string"
          }
        }
      }
    },
    "national_code": {
      "id": "national_code",
      "type": "string"
    },
    "subject_categories": {
      "id": "subject_categories",
      "type": "array",
      "items": {
        "id": "0",
        "type": "string"
      }
    },
    "current_status": {
      "id": "current_status",
      "type": "string"
    },
    "final_num": {
      "id": "final_num",
      "type": "string"
    },
    "publisher_country": {
      "id": "publisher_country",
      "type": "string"
    },
    "publisher_name": {
      "id": "publisher_name",
      "type": "string"
    },
    "eletronic_issn": {
      "id": "eletronic_issn",
      "type": "string"
    },
    "use_licenses": {
      "id": "use_licenses",
      "type": "object",
      "properties": {
        "reference_url": {
          "id": "reference_url",
          "type": "string"
        },
        "disclaimer": {
          "id": "disclaimer",
          "type": "string"
        },
        "license_code": {
          "id": "license_code",
          "type": "string"
        }
      }
    },
    "jid": {
      "id": "jid",
      "type": "string"
    },
    "title": {
      "id": "title",
      "type": "string"
    },
    "publisher_city": {
      "id": "publisher_city",
      "type": "string"
    },
    "final_year": {
      "id": "final_year",
      "type": "string"
    },
    "scielo_issn": {
      "id": "scielo_issn",
      "type": "string"
    },
    "collections": {
      "id": "collections",
      "type": "array",
      "items": {
        "id": "0",
        "type": "object",
        "properties": {
          "acronym": {
            "id": "acronym",
            "type": "string"
          },
          "name": {
            "id": "name",
            "type": "string"
          }
        }
      }
    },
    "init_year": {
      "id": "init_year",
      "type": "string"
    },
    "other_titles": {
      "id": "other_titles",
      "type": "array",
      "items": {
        "id": "0",
        "type": "object",
        "properties": {
          "category": {
            "id": "category",
            "type": "string"
          },
          "title": {
            "id": "title",
            "type": "string"
          }
        }
      }
    },
    "init_vol": {
      "id": "init_vol",
      "type": "string"
    },
    "updated": {
      "id": "updated",
      "type": "object",
      "properties": {}
    },
    "acronym": {
      "id": "acronym",
      "type": "string"
    },
    "timeline": {
      "id": "timeline",
      "type": "array",
      "items": {
        "id": "0",
        "type": "object",
        "properties": {
          "status": {
            "id": "status",
            "type": "string"
          },
          "reason": {
            "id": "reason",
            "type": "string"
          },
          "since": {
            "id": "since",
            "type": "object",
            "properties": {}
          }
        }
      }
    },
    "issue_count": {
      "id": "issue_count",
      "type": "integer"
    },
    "last_issue": {
      "id": "last_issue",
      "type": "object",
      "properties": {
        "start_month": {
          "id": "start_month",
          "type": "integer"
        },
        "iid": {
          "id": "iid",
          "type": "string"
        },
        "number": {
          "id": "number",
          "type": "string"
        },
        "label": {
          "id": "label",
          "type": "string"
        },
        "volume": {
          "id": "volume",
          "type": "string"
        },
        "end_month": {
          "id": "end_month",
          "type": "integer"
        },
        "bibliographic_legend": {
          "id": "bibliographic_legend",
          "type": "string"
        },
        "year": {
          "id": "year",
          "type": "integer"
        },
        "sections": {
          "id": "sections",
          "type": "array",
          "items": {
            "id": "8",
            "type": "string"
          }
        }
      }
    },
    "publisher_state": {
      "id": "publisher_state",
      "type": "string"
    },
    "sponsors": {
      "id": "sponsors",
      "type": "array",
      "items": {
        "id": "0",
        "type": "string"
      }
    },
    "online_submission_url": {
      "id": "online_submission_url",
      "type": "string"
    },
    "index_at": {
      "id": "index_at",
      "type": "array",
      "items": {}
    },
    "study_areas": {
      "id": "study_areas",
      "type": "array",
      "items": {
        "id": "0",
        "type": "string"
      }
    },
    "init_num": {
      "id": "init_num",
      "type": "string"
    },
    "social_networks": {
      "id": "social_networks",
      "type": "array",
      "items": {}
    },
    "created": {
      "id": "created",
      "type": "object",
      "properties": {}
    },
    "final_vol": {
      "id": "final_vol",
      "type": "string"
    },
    "short_title": {
      "id": "short_title",
      "type": "string"
    },
    "subject_descriptors": {
      "id": "subject_descriptors",
      "type": "array",
      "items": {
        "id": "1",
        "type": "string"
      }
    },
    "title_iso": {
      "id": "title_iso",
      "type": "string"
    },
    "_id": {
      "id": "_id",
      "type": "string"
    },
    "print_issn": {
      "id": "print_issn",
      "type": "string"
    }
  },
  "required": [
    "copyrighter",
    "mission",
    "national_code",
    "subject_categories",
    "current_status",
    "final_num",
    "publisher_country",
    "publisher_name",
    "eletronic_issn",
    "use_licenses",
    "jid",
    "title",
    "publisher_city",
    "final_year",
    "scielo_issn",
    "collections",
    "init_year",
    "other_titles",
    "init_vol",
    "updated",
    "acronym",
    "timeline",
    "issue_count",
    "last_issue",
    "publisher_state",
    "sponsors",
    "online_submission_url",
    "index_at",
    "study_areas",
    "init_num",
    "social_networks",
    "created",
    "final_vol",
    "short_title",
    "subject_descriptors",
    "title_iso",
    "_id",
    "print_issn"
  ]
}

=== DalavanCloud/opac_schema/docs/v1/journal/sample.json
{
  "copyrighter": "Escola Nacional de Sa\\u00fade P\\u00fablica, Funda\\u00e7\\u00e3o Oswaldo Cruz",
  "mission": [
    {
      "description": "Publicar art\\u00edculos originales que contribuyan al estudio de la salud p\\u00fablica en general y de disciplinas afines como epidemiolog\\u00eda, nutrici\\u00f3n, parasitolog\\u00eda, ecolog\\u00eda y control de vectores, salud ambiental, pol\\u00edticas p\\u00fablicas y planificaci\\u00f3n en el \\u00e1mbito de la salud, ciencias sociales aplicadas a la salud, entre otras.",
      "language": "es"
    },
    {
      "description": "Publicar artigos originais que contribuam para o estudo da sa\\u00fade p\\u00fablica em geral e disciplinas afins, como epidemiologia, nutri\\u00e7\\u00e3o, parasitologia, ecologia e controles de vetores, sa\\u00fade ambiental, pol\\u00edticas p\\u00fablicas e planejamento em sa\\u00fade, ci\\u00eancias sociais aplicadas \\u00e0 sa\\u00fade, dentre outras.",
      "language": "pt"
    },
    {
      "description": "To publish original articles that contribute to the study of public health in general and to related disciplines such as epidemiology, nutrition, parasitology,vector ecology and control, environmental health, public polices and health planning, social sciences applied to health, and others.",
      "language": "en"
    }
  ],
  "national_code": "081953-0",
  "subject_categories": [
    "Health Policy & Services"
  ],
  "current_status": "current",
  "final_num": "",
  "publisher_country": "BR",
  "publisher_name": "Escola Nacional de Sa\\u00fade P\\u00fablica Sergio Arouca, Funda\\u00e7\\u00e3o Oswaldo Cruz",
  "eletronic_issn": "",
  "use_licenses": {
    "reference_url": "",
    "disclaimer": "<a rel=\"license\" href=\"\" \">Licencia Creative Commons</a>",
    "license_code": "BY-NC"
  },
  "jid": "3aa91899e58a42648091ffc5b741c86e",
  "title": "Cadernos de Sa\\u00fade P\\u00fablica",
  "publisher_city": "Rio de Janeiro",
  "final_year": "",
  "scielo_issn": "print",
  "collections": [
    {
      "acronym": "spa",
      "name": "Sa\\u00fade P\\u00fablica"
    }
  ],
  "init_year": "1985",
  "other_titles": [
    {
      "category": "other",
      "title": "Cad Saude Publica"
    }
  ],
  "init_vol": "1",
  "updated": {},
  "acronym": "csp",
  "timeline": [
    {
      "status": "current",
      "reason": "",
      "since": {}
    }
  ],
  "issue_count": 240,
  "last_issue": {
    "start_month": 9,
    "iid": "3dc9f72fa42545fcba6656faf0a6825a",
    "number": "9",
    "label": "30 (9)",
    "volume": "30",
    "end_month": 9,
    "bibliographic_legend": "Cad. sa\\u00fade p\\u00fablica vol.30 n.9 Rio de Janeiro Sep/Sep 2014",
    "year": 2014,
    "sections": [
      "Errata",
      "Erratum",
      "Article",
      "Artigo",
      "Review",
      "Perspectivas",
      "Editorial (Escolha das Editoras)",
      "Brief Communication",
      "Comunica\\u00e7\\u00e3o Breve"
    ]
  },
  "publisher_state": "RJ",
  "sponsors": [
    "CNPq - Conselho Nacional de Desenvolvimento Cient\\u00edfico e Tecnol\\u00f3gico "
  ],
  "online_submission_url": "",
  "index_at": [],
  "study_areas": [
    "Health Sciences"
  ],
  "init_num": "1",
  "social_networks": [],
  "created": {},
  "final_vol": "",
  "short_title": "Cad. Sa\\u00fade P\\u00fablica",
  "subject_descriptors": [
    "saude publica\\r",
    "saude coletiva"
  ],
  "title_iso": "Cad. sa\\u00fade p\\u00fablica",
  "_id": "3aa91899e58a42648091ffc5b741c86e",
  "print_issn": "0102-311X"
}
