=== DalavanCloud/opac_schema/docs/v1/issue/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "",
  "type": "object",
  "properties": {
    "_id": {
      "id": "/_id",
      "type": "string"
    },
    "iid": {
      "id": "/iid",
      "type": "string"
    },
    "journal_jid": {
      "id": "/journal_jid",
      "type": "string"
    },
    "sections": {
      "id": "/sections",
      "type": "array",
      "items": []
    },
    "use_licenses": {
      "id": "/use_licenses",
      "type": "object",
      "properties": {
        "license_code": {
          "id": "/use_licenses/license_code",
          "type": "string"
        },
        "reference_url": {
          "id": "/use_licenses/reference_url",
          "type": "string"
        },
        "disclaimer": {
          "id": "/use_licenses/disclaimer",
          "type": "string"
        }
      }
    },
    "volume": {
      "id": "/volume",
      "type": "string"
    },
    "number": {
      "id": "/number",
      "type": "string"
    },
    "created": {
      "id": "/created",
      "type": "object",
      "properties": {}
    },
    "updated": {
      "id": "/updated",
      "type": "object",
      "properties": {}
    },
    "type": {
      "id": "/type",
      "type": "string"
    },
    "year": {
      "id": "/year",
      "type": "integer"
    },
    "label": {
      "id": "/label",
      "type": "string"
    },
    "order": {
      "id": "/order",
      "type": "integer"
    },
    "bibliographic_legend": {
      "id": "/bibliographic_legend",
      "type": "string"
    }
  },
  "required": [
    "_id",
    "iid",
    "journal_jid",
    "sections",
    "use_licenses",
    "volume",
    "number",
    "created",
    "updated",
    "type",
    "year",
    "label",
    "order",
    "bibliographic_legend"
  ]
}

=== DalavanCloud/opac_schema/docs/v1/issue/sample.json
{
    "_id": "3af7fbe7924e4377a9dad41a65e5e4bf",
    "iid": "3af7fbe7924e4377a9dad41a65e5e4bf",
    "journal_jid": "3aa91899e58a42648091ffc5b741c86e",
    "sections": [],
    "use_licenses": {
        "license_code": "BY-NC",
        "reference_url": "",
        "disclaimer": "<a rel=\"license\" href=\"http://creativecommons.org/licenses/by-nc/3.0/\"><img alt=\"Creative Commons License\" style=\"border-width:0\" src=\"http://i.creativecommons.org/l/by-nc/3.0/80x15.png\" /></a> Todo el contenido de esta revista, excepto d\\u00f3nde est\\u00e1 identificado, est&#225; bajo una <a rel=\"license\" href=\"http://creativecommons.org/licenses/by-nc/3.0/\">Licencia Creative Commons</a>"
    },
    "volume": "30",
    "number": "11",
    "created": {
        "$date": 1432117835334
    },
    "updated": {
        "$date": 1445876198890
    },
    "type": "regular",
    "year": 2014,
    "label": "30 (11)",
    "order": 12,
    "bibliographic_legend": "Cad. sa\\u00fade p\\u00fablica vol.30 n.11 Rio de Janeiro 2014"
}
