=== DalavanCloud/opac_schema/docs/v1/article/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "",
  "type": "object",
  "properties": {
    "_id": {
      "id": "/_id",
      "type": "string"
    },
    "aid": {
      "id": "/aid",
      "type": "string"
    },
    "issue_iid": {
      "id": "/issue_iid",
      "type": "string"
    },
    "journal_jid": {
      "id": "/journal_jid",
      "type": "string"
    },
    "title": {
      "id": "/title",
      "type": "string"
    },
    "section": {
      "id": "/section",
      "type": "string"
    },
    "is_aop": {
      "id": "/is_aop",
      "type": "boolean"
    },
    "created": {
      "id": "/created",
      "type": "object",
      "properties": {}
    },
    "updated": {
      "id": "/updated",
      "type": "object",
      "properties": {}
    },
    "htmls": {
      "id": "/htmls",
      "type": "array",
      "items": {
        "id": "/htmls/0",
        "type": "object",
        "properties": {
          "language": {
            "id": "/htmls/0/language",
            "type": "string"
          },
          "source": {
            "id": "/htmls/0/source",
            "type": "string"
          }
        }
      }
    },
    "domain_key": {
      "id": "/domain_key",
      "type": "string"
    }
  },
  "required": [
    "_id",
    "aid",
    "issue_iid",
    "journal_jid",
    "title",
    "section",
    "is_aop",
    "created",
    "updated",
    "htmls",
    "domain_key"
  ]
}

=== DalavanCloud/opac_schema/docs/v1/article/sample.json
{
    "_id": "111dee8528d0405fb9e6571a0a81c263",
    "aid": "111dee8528d0405fb9e6571a0a81c263",
    "issue_iid": "3af7fbe7924e4377a9dad41a65e5e4bf",
    "journal_jid": "3aa91899e58a42648091ffc5b741c86e",
    "title": "As Ci\\u00eancias Sociais e Humanas em Sa\\u00fade na ABRASCO: a\\n\\t\\t\\t\\t\\tconstru\\u00e7\\u00e3o de um pensamento social em sa\\u00fade",
    "section": "Artigo",
    "is_aop": false,
    "created": {
        "$date": 1435158217158
    },
    "updated": {
        "$date": 1439920623798
    },
    "htmls": [
        {
            "language": "pt",
            "source": "<!DOCTYPE html><html lang=\"pt\"><head><title>Cad Saude Publica - As Ci\\u00eancias Sociais e Humanas em Sa\\u00fade na ABRASCO: a\\n\\t\\t\\t\\t\\tconstru\\u00e7\\u00e3o de um pensamento social em sa\\u00fade</title></head><body></body></html>"
        }
    ],
    "domain_key": "cadernos-de-saude-publica_30_11_2014_2298_none_2308_none_none"
}
